/*
 * Esta clase representa una interfaz gráfica que permite visualizar e interactuar con las generaciones de un árbol genealógico. 
    Los usuarios pueden seleccionar una generación específica desde un combo box y ver los integrantes de la misma.
 */
package Interfaz;

import Clases.Lista;
import Clases.ListaArray;
import Clases.Nodo;
import Clases.Persona;
import Clases.Tree;
import Interfaz.WindowManager;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import proyecto2.HashTableTitles;


public class TitleSearch extends javax.swing.JFrame {

    private HashTableTitles titlesHashTable;
    private Lista currentResults;

    /**
     * Constructor de la clase. Inicializa los componentes de la interfaz y asigna el árbol genealógico. 
     * También se registra la ventana y se establece el comportamiento al cerrar la ventana.
     */
    public TitleSearch() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SearchText = new javax.swing.JTextField();
        BuscarPersonajesBtn = new javax.swing.JLabel();
        BuscarBtn = new javax.swing.JLabel();
        VerDatosBtn = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchResults = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        PersonSelect = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextActionPerformed(evt);
            }
        });
        jPanel1.add(SearchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 400, 40));

        BuscarPersonajesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BuscarPersonajesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarPersonajesBtnMouseClicked(evt);
            }
        });
        jPanel1.add(BuscarPersonajesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 150, 30));

        BuscarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BuscarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarBtnMouseClicked(evt);
            }
        });
        jPanel1.add(BuscarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 150, 30));

        VerDatosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerDatosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerDatosBtnMouseClicked(evt);
            }
        });
        jPanel1.add(VerDatosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 150, 30));

        jScrollPane1.setViewportView(SearchResults);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 250, 170));

        jScrollPane2.setViewportView(PersonSelect);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 260, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/5.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setTitlesHashTable(HashTableTitles titlesHashTable) {
        this.titlesHashTable = titlesHashTable;
    }
    
    private void SearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextActionPerformed

    private void BuscarPersonajesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarPersonajesBtnMouseClicked
        currentResults = titlesHashTable.get(SearchResults.getSelectedValue());
        String[] aux = new String[currentResults.getSize()];
        Nodo r = currentResults.getHead();
        int i = 0;
        while (r != null){
            aux[i] = ((Persona) r.getElement()).getNombre();
            i++;
            r = r.getNext();
        }
        PersonSelect.setListData(aux);
        // aquí debería enviarte a otra selección para luego mostrar la informacion de la persona
    }//GEN-LAST:event_BuscarPersonajesBtnMouseClicked

    private void BuscarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarBtnMouseClicked
        SearchResults.setListData(titlesHashTable.getMatch(SearchText.getText()));
    }//GEN-LAST:event_BuscarBtnMouseClicked

    private void VerDatosBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerDatosBtnMouseClicked
        Persona persona = (Persona) currentResults.get(PersonSelect.getSelectedValue());
        StringBuilder info = new StringBuilder();
        info.append("Nombre: ").append(persona.getNombre()).append("\n");
        info.append("Apodo: ").append(persona.getApodo()).append("\n");
        ListaArray atributos = persona.getAtributos();
        for (int i = 0; i < atributos.getMaxSize(); i++) {
            info.append(atributos.toStringAt(i)).append("\n");
        }
        JOptionPane.showMessageDialog(rootPane, info);
    }//GEN-LAST:event_VerDatosBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TitleSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TitleSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TitleSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TitleSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TitleSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuscarBtn;
    private javax.swing.JLabel BuscarPersonajesBtn;
    private javax.swing.JList<String> PersonSelect;
    private javax.swing.JList<String> SearchResults;
    private javax.swing.JTextField SearchText;
    private javax.swing.JLabel VerDatosBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
