/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Clases.ListaArray;
import Clases.NodoArray;
import Clases.NodoTree;
import Clases.Persona;
import Clases.Tree;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import proyecto2.HashTable;

/**
 *
 * @author xc2do
 */
public class VerGeneracionYRegistro extends javax.swing.JFrame {

    private Tree arbolGenealogico;
    private HashTable personaHashTable; //declara la variable personaHashTable

    /**
     * Creates new form VerGeneracionYRegistro
     */
    public VerGeneracionYRegistro(Tree arbolGenealogico, HashTable personaHashTable) {
        initComponents();
        this.arbolGenealogico = arbolGenealogico;
        this.personaHashTable = personaHashTable;
        llenarComboBoxGeneraciones();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SeleccionarBtn = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SeleccionarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SeleccionarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeleccionarBtnMouseClicked(evt);
            }
        });
        getContentPane().add(SeleccionarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 150, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 230, 40));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 410, 220));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 230, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/3_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int generacion = jComboBox1.getSelectedIndex() + 1;
        ListaArray integrantes = arbolGenealogico.obtenerIntegrantesDeGeneracion(generacion, 100); // Ajusta el tamaño máximo según sea necesario 
        DefaultListModel<String> model = new DefaultListModel<>();
        NodoArray[] arrayIntegrantes = integrantes.getArray();
        for (int i = 0; i < integrantes.getSize(); i++) {
            NodoArray nodoIntegrante = arrayIntegrantes[i];
            if (nodoIntegrante != null) {
                Persona persona = (Persona) nodoIntegrante.getElement();
                model.addElement(persona.getNombre());
            }
        }
        jList1.setModel(model);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void SeleccionarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeleccionarBtnMouseClicked
        String nombrePersonajeSeleccionado = jList1.getSelectedValue();
        if (nombrePersonajeSeleccionado != null && !nombrePersonajeSeleccionado.isEmpty()) {
            for (NodoTree nodo : personaHashTable.getTable()) {
                if (nodo != null) {
                    Persona persona = (Persona) nodo.getElement();
                    if (persona.getNombre().equals(nombrePersonajeSeleccionado)) {
                        mostrarDatosPersona(persona);
                        break;
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un personaje", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SeleccionarBtnMouseClicked

    private void mostrarDatosPersona(Persona persona) {
        StringBuilder info = new StringBuilder();
        info.append("Nombre: ").append(persona.getNombre()).append("\n");
        info.append("Apodo: ").append(persona.getApodo()).append("\n");
        ListaArray atributos = persona.getAtributos();
        for (int i = 0; i < atributos.getMaxSize(); i++) {
            info.append(atributos.toStringAt(i)).append("\n");
        }
        jTextArea1.setText(info.toString());
    }

    private void llenarComboBoxGeneraciones() {
        jComboBox1.removeAllItems();
        int alturaArbol = arbolGenealogico.obtenerAlturaArbol();
        for (int i = 1; i <= alturaArbol; i++) { // Suponiendo un máximo de 10 generaciones 
            jComboBox1.addItem("Generacion " + i);
            System.out.println("Aniadiendo al ComboBox: Generacion " + i);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerGeneracionYRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerGeneracionYRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerGeneracionYRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerGeneracionYRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tree arbolGenealogico = new Tree(); // Crea una instancia de Tree o pásala desde otra parte del código
                HashTable personaHashTable = new HashTable(); //la HashTable también
                new VerGeneracionYRegistro(arbolGenealogico, personaHashTable).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SeleccionarBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
